FROM node:14.17.1

LABEL version="1.0"
LABEL description="This is the base docker image for the Node Backend API."
LABEL maintainer = ["troniez"]

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]
RUN ls
RUN npm install --production
COPY . .

EXPOSE 1337

CMD ["node", "app.js"]
