FROM node:14.17.1

LABEL version="1.0"
LABEL description="This is the base docker image for the Frontend React app."
LABEL maintainer = ["troniez"]

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]

RUN npm install --production

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
