version: "3.7"
services:
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./source_frontend
      dockerfile: ./Dockerfile
    volumes:
      - /app/node_modules
      - ./source_frontend:/app
    ports:
      - "3000:3000"
    links:
      - "backend"

  backend:
    build:
      context: ./source_backend
      dockerfile: ./Dockerfile
    volumes:
      - ./source_backend:/api
    ports:
      - "1337:1337"

