version: "3.8"
services:
  web:
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpack

  webpack:
    build: .
    command: ./bin/webpack-dev-server --inline true
    volumes:
      - .:/app
    ports:
      - '3035:3035'

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

